[Watcher]
GamePath = 'E:\Games\Tencent Games\VALORANT\live\VALORANT.exe'
Width = 1568
Height = 1080
Fps = 144

[Valorant]
LauncherPath = ""
GamePath = 'E:\Games\Tencent Games\VALORANT\live'

[Development]
Debug = true